"""Map tham số thiếu → câu hỏi người viết sizing trả lời được (Fix 4, 2026-09-10).

Lượt chạy HỆ THỐNG 2026-09-09 cho ra 302 finding "Chưa kiểm được" mà gợi ý dõi theo
tên biến Python: "Bổ sung `so_node` vào bản sizing". Người viết sizing không biết
`so_node` là gì — họ biết trả lời câu hỏi. Map này diễn đạt lại `tham_so_goi_y`
trong `config/rules.yaml` (NT3: gợi ý là dữ liệu người nghiệp vụ sửa được; file
này chỉ là fallback khi khoá chưa có trong rules.yaml).
"""
from __future__ import annotations

# Fallback khi `tham_so_goi_y` chưa có khoá. Khoá = tên tham số C3; giá trị =
# câu hỏi tiếng Việt mà người viết sizing trả lời được.
_CAU_HOI: dict[str, str] = {
    # --- cờ có/không ---
    "la_ho_so_xin_cap_phat": "Hồ sơ này là yêu cầu cấp phát mới hay chỉ xin thẩm định bản định cỡ?",
    "la_ho_so_thu_hoi": "Hồ sơ này có phải hồ sơ thu hồi tài nguyên không?",
    "la_he_thong_noi_bo": "Hệ thống chạy nội bộ hay hướng ra ngoài internet?",
    "tren_cloud_tap_doan": "Hệ thống có chạy trên cloud tập đoàn không?",
    "tren_ha_tang_tap_doan": "Chạy trên hạ tầng tập đoàn hay hạ tầng riêng của đơn vị?",
    "dang_dinh_co": "Đang định cỡ cho tải hiện tại hay tải dự kiến tương lai?",
    "hinh_thuc_cap_phat": "Tài nguyên cấp phát theo hình thức nào (máy ảo/ảo hoá, máy chủ vật lý, container)?",
    "mo_hinh_redis": "Redis triển khai theo mô hình nào (standalone, sentinel, cluster)?",
    "mo_hinh_trien_khai": "Hệ thống triển khai theo mô hình nào (standalone, cluster, HA)?",
    "co_phan_vung_data": "Có phân vùng dữ liệu (data) riêng không?",
    "co_phan_vung_log": "Có phân vùng log riêng không?",
    "co_phan_vung_backup": "Có phân vùng backup riêng không?",
    "co_dc_dr": "Có quy hoạch dự phòng liên cơ sở (DR) không?",
    "co_khai_du_phong_noi_site": "Có khai báo dự phòng nội site (trong cùng trạm) không?",
    "co_he_tham_chieu": "Có hệ tham chiếu (định cỡ tương tự đã duyệt) làm sở cứ không?",
    "co_ket_qua_2017": "Có dùng kết quả benchmark 2017 làm sở cứ không?",
    "co_kiem_thu_hieu_nang": "Có kết quả kiểm thử hiệu năng (bản kiểm thử, báo cáo đo) không?",
    "co_dung_so_lieu_kiem_thu": "Số liệu định cỡ có lấy từ đo kiểm thử thực tế không?",
    "co_so_lieu_do_thuc_te": "Có số liệu đo tải thực tế (monitoring, load test) không?",
    "co_neu_iops": "Tài liệu có nêu IOPS không?",
    "co_neu_latency": "Tài liệu có nêu latency không?",
    "co_duong_ra_public": "Hệ thống có đường ra public (internet) không?",
    "co_dinh_co_firewall": "Tài liệu có phần định cỡ firewall không?",
    "co_dinh_co_lb": "Tài liệu có phần định cỡ load balancer không?",
    "co_ap_quota": "Có phần định cỡ AP/Quota không?",
    "dung_tai_nguyen_danh_rieng": "Tài nguyên dành riêng cho hệ thống hay dùng chung với hệ khác?",
    "dung_nhieu_ram": "Có thành phần nào tiêu thụ RAM đặc biệt lớn không?",
    "he_hieu_nang_cao": "Có thành phần nào yêu cầu hiệu năng cao đặc biệt không?",
    "chuan_spec": "Dùng chuẩn SPEC nào để quy đổi hiệu năng CPU (SPECcpu 2006/2017)?",
    "vm_hieu_nang_cao": "Có máy ảo nào thuộc nhóm hiệu năng cao không?",
    # --- số lượng máy/node ---
    "so_node": "Khai rõ số node của phân hệ (bao nhiêu máy hoạt động + bao nhiêu dự phòng)?",
    "so_master": "Khai rõ số node master (ví dụ cụm k8s: bao nhiêu master)?",
    "so_slave_moi_master": "Khai rõ số slave/worker cho mỗi master?",
    "so_slave_yeu_cau": "Số slave/worker tối thiểu yêu cầu là bao nhiêu?",
    "so_broker": "Khai rõ số broker Kafka trong cụm.",
    "so_ban": "Khai rõ số bản sao lưu (số copy backup) định tạo.",
    "so_thiet_bi": "Khai rõ số thiết bị mạng (switch/firewall/LB) dự kiến lắp đặt.",
    "so_may_du_phong": "Khai rõ số máy chủ dự phòng (dạng N+1/N+2 thì ghi rõ hệ số).",
    "so_may_hoat_dong": "Khai rõ số máy chủ hoạt động (không tính dự phòng).",
    "tong_may_khai": "Khai rõ tổng số máy chủ (hoạt động + dự phòng).",
    "so_dau_doc": "Khai rõ số đầu đọc băng (tape drive) dự kiến.",
    "so_key": "Khai rõ số key/license cấp phát.",
    "so_key_poc": "Số key/TPS dùng cho POC là bao nhiêu?",
    "so_key_khai": "Số key dùng cho chạy thật là bao nhiêu?",
    "so_port": "Khai rõ số cổng (port) thiết bị mạng cần cấp.",
    "so_port_firewall_khai": "Khai rõ số cổng firewall cần cấp.",
    "so_port_lan_khai": "Khai rõ số cổng LAN cần cấp.",
    "so_port_san_khai": "Khai rõ số cổng sẵn có đang dùng.",
    "so_rack_khai": "Khai rõ số rack cần cấp.",
    "so_bo_pdu": "Khai rõ số bộ PDU cần cấp.",
    "so_tape_toan_bo_khai": "Khai rõ số băng từ (tape) cho sao lưu toàn bộ.",
    "so_tape_gia_tang_khai": "Khai rõ số băng từ cho sao lưu gia tăng.",
    "so_cleaning_tape_khai": "Khai rõ số băng từ làm sạch (cleaning tape).",
    "so_driver_khai": "Khai rõ số drive (ổ đĩa) của hệ lưu trữ.",
    "so_duong_ket_noi_khai": "Khai rõ số đường kết nối (link) tới thiết bị lưu trữ.",
    "so_host_vat_ly": "Khai rõ số máy chủ vật lý (host) dự kiến.",
    "so_o_luu_du_lieu": "Khai rõ số ổ đĩa lưu trữ dữ liệu.",
    "so_o_theo_dung_luong": "Khai rõ số ổ tính theo nhu cầu dung lượng.",
    "so_o_theo_hieu_nang": "Khai rõ số ổ tính theo nhu cầu hiệu năng (IOPS).",
    "so_o_theo_dung_luong_khai": "Khai rõ số ổ theo dung lượng đã dùng khi tính.",
    "so_o_theo_hieu_nang_khai": "Khai rõ số ổ theo hiệu năng đã dùng khi tính.",
    "so_o_hotspare": "Khai rõ số ổ hot-spare dự phòng.",
    "so_o_cung_loai": "Khai rõ số ổ cùng loại trong hệ lưu trữ.",
    "so_mau": "Khai rõ số mẫu (instance) dự kiến cấp.",
    "so_lan_moi_mau": "Khai rõ số lần đo cho mỗi mẫu kiểm thử.",
    # --- CPU/RAM ---
    "or_cpu_khai": "Khai rõ hệ số overcommit CPU của hạ tầng ảo hoá (ví dụ 4:1).",
    "or_ram_khai": "Khai rõ hệ số overcommit RAM của hạ tầng ảo hoá (ví dụ 1.5:1).",
    "cpu_95th": "Nêu rõ tải CPU dùng làm sở cứ định cỡ (95th percentile, ví dụ «tải CPU 60%»).",
    "ram_95th": "Nêu rõ tải RAM dùng làm sở cứ định cỡ (95th percentile).",
    "cpu_95th_ty_le": "Nêu rõ % tải CPU 95th làm sở cứ.",
    "ram_95th_ty_le": "Nêu rõ % tải RAM 95th làm sở cứ.",
    "ram_su_dung_gb": "Nêu rõ RAM đang sử dụng thực tế (GB).",
    "ram_su_dung_khai_gb": "Nêu rõ RAM sử dụng thực tế (GB) và thời điểm đo.",
    "ram_cau_hinh_gb": "Nêu rõ RAM cấu hình đề xuất cho máy chủ.",
    "ram_moi_node_gb": "Khai rõ RAM cho mỗi node.",
    "ram_broker_khai": "Khai rõ RAM cho mỗi broker Kafka.",
    "vcpu_broker_khai": "Khai rõ vCPU cho mỗi broker Kafka.",
    "so_vcpu_khai": "Khai rõ số vCPU cấp cho máy ảo.",
    "vcpu_moi_vm": "Khai rõ số vCPU cho mỗi máy ảo.",
    "ram_moi_vm_gb": "Khai rõ RAM (GB) cho mỗi máy ảo.",
    "vcpu_may_ao": "Khai rõ số vCPU cho mỗi máy ảo.",
    "so_core_1_cpu": "Khai rõ số core của một CPU vật lý.",
    "so_thread_1_core": "Khai rõ số thread mỗi core CPU.",
    "so_cpu_vat_ly": "Khai rõ số CPU vật lý của máy chủ.",
    "cint_rated_1_cpu": "Nêu rõ điểm SPECrate của một CPU (để quy đổi Cint).",
    "spec_1_cpu": "Nêu rõ điểm SPEC của một CPU vật lý (để quy đổi hiệu năng).",
    "spec_1_vcpu_khai": "Nêu rõ điểm SPEC mỗi vCPU dùng làm sở cứ.",
    "spec2006": "Nêu rõ điểm SPECcpu 2006 của CPU dùng làm sở cứ.",
    "he_so_quy_doi": "Nêu rõ hệ số quy đổi từ điểm SPEC sang Cint.",
    "chi_so_chon": "Nêu rõ chỉ số hiệu năng đã chọn làm sở cứ.",
    "chi_so_dung_cho_loai_he": "Nêu rõ chỉ số hiệu năng dùng cho loại hệ thống này.",
    "loai_he_thong": "Hệ thống thuộc loại nào (giao dịch, xử lý dữ liệu, gateway…)?",
    # --- hệ số ---
    "he_so_kpi": "Nêu rõ hệ số KPI (cấu hình đề xuất = tải đo được × hệ số).",
    "he_so_kpi_cpu_khai": "Nêu rõ hệ số KPI dùng cho CPU.",
    "he_so_kpi_ram_khai": "Nêu rõ hệ số KPI dùng cho RAM.",
    "he_so_kpi_dia_khai": "Nêu rõ hệ số KPI dùng cho dung lượng đĩa.",
    "he_so_so_sanh": "Nêu rõ hệ số so sánh với hệ tham chiếu.",
    "he_so_so_sanh_khai": "Nêu rõ hệ số so sánh đã dùng khi tính.",
    "he_so_replica": "Khai rõ hệ số replica (số bản sao dữ liệu) của cụm.",
    "he_so_nen": "Nêu rõ hệ số nén dữ liệu áp dụng.",
    "he_so_sai_so_khai": "Nêu rõ hệ số sai số cho phép khi tính.",
    "ty_le_overcommit": "Nêu rõ hệ số overcommit của hạ tầng (CPU/RAM).",
    "ty_le_overcommit_khai": "Nêu rõ hệ số overcommit CPU đã dùng khi tính.",
    "ty_le_overcommit_ram_khai": "Nêu rõ hệ số overcommit RAM đã dùng khi tính.",
    "tong_spec_thanh_phan": "Nêu rõ tổng điểm SPEC của các thành phần để quy đổi CPU.",
    "tong_tai_peak_khai": "Nêu rõ tải đỉnh (peak) đã dùng khi tính.",
    "tong_tai_cac_nghiep_vu": "Liệt kê tải của từng nghiệp vụ (để tổng ra tải toàn hệ).",
    "tong_su_dung": "Nêu rõ tổng mức sử dụng tài nguyên hiện tại.",
    "tong_tai_nguyen": "Nêu rõ tổng tài nguyên cần cấp (CPU/RAM/disk) trước khi chia máy.",
    "tong_tai_nguyen_khai": "Nêu rõ tổng tài nguyên đã dùng khi tính cấu hình.",
    "tong_toan_he": "Nêu rõ tổng tải toàn hệ thống.",
    "tong_cac_phan_he": "Liệt kê tải từng phân hệ để tổng ra toàn hệ.",
    "tong_thanh_phan_dung_chung": "Liệt kê tải của các thành phần dùng chung.",
    "chu_ky_tang_truong_thang": "Nêu rõ chu kỳ tăng trưởng dữ liệu (GB/tháng).",
    "chu_ky_dam_bao_thang": "Nêu rõ thời gian cam kết bảo hành/bảo trì (tháng).",
    "thoi_gian_giu_gio": "Nêu rõ thời gian giữ dữ liệu giờ cao điểm (để tính peak).",
    "thoi_gian_yeu_cau_giay": "Nêu rõ thời gian yêu cầu hoàn thành restore (giây).",
    "thong_so_he_moi": "Nêu rõ thông số của hệ mới (hệ đang định cỡ).",
    "thong_so_he_tham_chieu": "Nêu rõ thông số của hệ tham chiếu để so sánh.",
    "thoi_gian_giu_gio_cao_diem": "Nêu rõ thời gian giữ giờ cao điểm khi đo.",
    # --- dung lượng ---
    "tong_du_lieu_gb": "Nêu rõ tổng dung lượng dữ liệu hiện có (GB).",
    "du_lieu_30_phut_gb": "Nêu rõ dung lượng dữ liệu sinh ra trong 30 phút (GB).",
    "du_lieu_30_phut_khai_gb": "Nêu rõ dung lượng dữ liệu 30 phút đã dùng khi tính Kafka.",
    "dung_luong_data_gb": "Nêu rõ dung lượng phân vùng dữ liệu (GB).",
    "dung_luong_backup_gb": "Nêu rõ dung lượng cần sao lưu (GB).",
    "dung_luong_backup_khai_gb": "Nêu rõ dung lượng sao lưu đã dùng khi tính (GB).",
    "dung_luong_toan_bo_gb": "Nêu rõ dung lượng sao lưu toàn bộ (full backup, GB).",
    "dung_luong_gia_tang_gb": "Nêu rõ dung lượng sao lưu gia tăng (GB).",
    "dung_luong_1_tape_gb": "Nêu rõ dung lượng lưu trữ của một băng từ (GB).",
    "dung_luong_giay_mbs": "Nêu rõ lượng dữ liệu sinh ra mỗi ngày (MB/s quy đổi).",
    "dung_luong_nas_khai_gb": "Nêu rõ dung lượng NAS cần cấp (GB).",
    "dung_luong_du_lieu_khai_gb": "Nêu rõ dung lượng dữ liệu đã dùng khi tính (GB).",
    "dung_luong_kafka_khai_mb": "Nêu rõ dung lượng dữ liệu Kafka đã dùng khi tính (MB).",
    "dung_luong_ram_gb": "Nêu rõ dung lượng RAM cần cấp (GB).",
    "dung_luong_1_ban_gb": "Nêu rõ dung lượng của một bản sao lưu (GB).",
    "dung_luong_1_o_gb": "Nêu rõ dung lượng của một ổ đĩa (GB).",
    "dung_luong_tho_gb": "Nêu rõ dung lượng thô của hệ lưu trữ (GB).",
    "dung_luong_kha_dung_gb": "Nêu rõ dung lượng khả dụng sau RAID (GB).",
    "dung_luong_dung_gb": "Nêu rõ dung lượng đang sử dụng (GB).",
    "dung_luong_restore_gb": "Nêu rõ dung lượng cần phục hồi (restore, GB).",
    "dung_luong_chuan_lto": "Nêu rõ dung lượng chuẩn của băng LTO dùng.",
    "tong_can_thiet_gb": "Nêu rõ tổng dung lượng cần thiết (GB).",
    "tong_luu_luong_dich_vu": "Nêu rõ TỔNG thông lượng dịch vụ đi qua FW/LB (Gbps/Mbps).",
    "luu_luong_dich_vu_khai": "Nêu rõ thông lượng dịch vụ đã dùng khi tính.",
    "thong_luong_firewall_khai": "Nêu rõ thông lượng firewall đã dùng khi tính.",
    "thong_luong_lb_khai": "Nêu rõ thông lượng load balancer đã dùng khi tính.",
    "thong_luong_thiet_bi_khai_mbps": "Nêu rõ thông lượng thiết bị đã dùng khi tính (Mbps).",
    "dai_thong_dung_min_gb": "Nêu rõ băng thông sử dụng tối thiểu (GB).",
    "dai_thong_dung_max_gb": "Nêu rõ băng thông sử dụng tối đa (GB).",
    # --- lưu trữ / ổ cứng / RAID ---
    "cau_hinh_moi_may_khai": "Nêu rõ cấu hình đề xuất cho mỗi máy chủ (CPU/RAM/disk).",
    "disk_moi_node_khai": "Khai rõ dung lượng đĩa cho mỗi node.",
    "loai_o": "Nêu rõ loại ổ đĩa dùng (NL-SAS/SAS/SSD/NVMe).",
    "cap_raid": "Nêu rõ cấp RAID dùng (RAID 5/6/10).",
    "ty_le_raid": "Nêu rõ hệ số RAID dùng khi tính dung lượng thô.",
    "ty_le_raid_khai": "Nêu rõ hệ số RAID đã dùng khi tính.",
    "ty_le_format_khai": "Nêu rõ hệ số định dạng (format) đã dùng khi tính.",
    "ty_le_sai_so_khai": "Nêu rõ hệ số sai số đã dùng khi tính.",
    "ty_le_du_phong_khai": "Nêu rõ hệ số dự phòng đã dùng khi tính.",
    "ty_le_dung_ssd": "Nêu rõ tỷ lệ dữ liệu nóng dùng SSD.",
    "ty_le_nen": "Nêu rõ tỷ lệ nén dữ liệu áp dụng.",
    "ty_le_doc_ghi_khai": "Nêu rõ tỷ lệ đọc/ghi áp dụng khi tính IOPS.",
    "ty_le_doc_khai": "Nêu rõ tỷ lệ đọc áp dụng khi tính IOPS.",
    "ty_le_ghi_khai": "Nêu rõ tỷ lệ ghi áp dụng khi tính IOPS.",
    "iops_95th": "Nêu rõ IOPS 95th đo được làm sở cứ.",
    "iops_toi_da": "Nêu rõ IOPS tối đa yêu cầu.",
    "iops_moi_o_khai": "Nêu rõ IOPS mỗi ổ dùng làm sở cứ.",
    "iops_toi_da_loai_o": "Nêu rõ IOPS tối đa của loại ổ đã chọn.",
    "iops_loai_o": "Nêu rõ IOPS của loại ổ đĩa dùng làm sở cứ.",
    "backend_iops": "Nêu rõ IOPS tầng backend của hệ lưu trữ.",
    "frontend_iops": "Nêu rõ IOPS tầng frontend của hệ lưu trữ.",
    "write_penalty": "Nêu rõ write penalty của cấp RAID dùng.",
    "write_penalty_khai": "Nêu rõ write penalty đã dùng khi tính.",
    "write_penalty_theo_raid": "Nêu rõ write penalty theo cấp RAID đã chọn.",
    "the_he_lto": "Nêu rõ thế hệ băng từ LTO dùng (LTO-7/LTO-8…).",
    "toc_do_1_tape_mbs": "Nêu rõ tốc độ đọc/ghi của một băng từ (MB/s).",
    "toc_do_1_duong_mbs": "Nêu rõ tốc độ của một đường kết nối lưu trữ (MB/s).",
    "toc_do_chuan_lto": "Nêu rõ tốc độ chuẩn của băng LTO dùng (MB/s).",
    "bang_thong_backup_gbs": "Nêu rõ băng thông đường sao lưu (GB/s).",
    "kich_co_goi_do_byte": "Nêu rõ kích cỡ gói dữ liệu (byte) dùng khi tính.",
    "kich_thuoc_ban_ghi_byte": "Nêu rõ kích thước bản ghi (byte) dùng khi tính.",
    "co_ghep_port": "Có gộp cổng (port channel) không?",
    "so_port_ghep": "Khai rõ số cổng gộp (port channel).",
    "tong_port_dich_vu": "Nêu rõ tổng cổng dịch vụ cần kết nối.",
    "tong_port_cac_zone": "Nêu rõ tổng cổng của các zone.",
    "port_ha": "Nêu rõ số cổng dự phòng (HA) của thiết bị.",
    "port_thiet_ke": "Nêu rõ số cổng thiết kế của thiết bị mạng.",
    "port_dung": "Nêu rõ số cổng đang sử dụng.",
    "port_active_1_thiet_bi": "Nêu rõ số cổng active trên mỗi thiết bị.",
    "port_kien_truc_mang": "Nêu rõ số cổng theo kiến trúc mạng.",
    "loai_switch_port": "Nêu rõ loại cổng switch dùng (1G/10G/25G…).",
    "loai_thiet_bi": "Nêu rõ loại thiết bị (switch/firewall/LB) cần cấp.",
    "bandwidth_port_mbps": "Nêu rõ băng thông mỗi cổng (Mbps).",
    "bandwidth_toi_thieu_theo_luu_luong": "Nêu rõ băng thông tối thiểu theo lưu lượng.",
    "tong_luu_luong_zone_up": "Nêu rõ lưu lượng zone hướng lên (Mbps).",
    "tong_luu_luong_zone_down": "Nêu rõ lưu lượng zone hướng xuống (Mbps).",
    "luu_luong_port_tb_mbps": "Nêu rõ lưu lượng trung bình mỗi cổng (Mbps).",
    "throughput_mbs": "Nêu rõ thông lượng (MB/s) dùng làm sở cứ định cỡ.",
    "throughput_thiet_ke": "Nêu rõ thông lượng thiết kế của thiết bị.",
    "throughput_dung": "Nêu rõ thông lượng đang sử dụng.",
    # --- messaging / key-value ---
    "cps": "Nêu rõ số kết nối mỗi giây (CPS) làm sở cứ định cỡ firewall/LB.",
    "luu_luong_1_cps": "Nêu rõ lưu lượng tương ứng mỗi CPS.",
    "tps": "Nêu rõ số giao dịch mỗi giây (TPS) làm sở cứ định cỡ.",
    "luu_luong_1_tps": "Nêu rõ lưu lượng tương ứng mỗi TPS.",
    # --- rack / vật lý ---
    "tong_ru": "Nêu rõ tổng chiều cao thiết bị (RU) cần cấp.",
    "ru_khai": "Nêu rõ chiều cao (RU) đã khai của thiết bị.",
    "ru_chuan_theo_loai": "Nêu rõ chiều cao chuẩn theo loại thiết bị.",
    "chieu_cao_u": "Nêu rõ chiều cao (U) của rack.",
    "chieu_rong_mm": "Nêu rõ chiều rộng (mm) của rack/thiết bị.",
    "chieu_sau_mm": "Nêu rõ chiều sâu (mm) của rack/thiết bị.",
    # --- dữ liệu đo ---
    "so_ngay_do": "Nêu rõ số ngày đo tải làm sở cứ.",
    "so_ngay_do_iops": "Nêu rõ số ngày đo IOPS làm sở cứ.",
    "datanode_95th": "Nêu rõ tải 95th của datanode làm sở cứ.",
    "so_lan_moi_mau": "Nêu rõ số lần đo mỗi mẫu kiểm thử.",
    # --- phân bổ CPU/RAM trong máy chủ vật lý ---
    "core_danh_cho_hdh": "Nêu rõ số core dành cho hệ điều hành (không tính cho VM).",
    "ram_danh_cho_hdh_gb": "Nêu rõ RAM (GB) dành cho hệ điều hành.",
    "cpu_danh_cho_hypervisor": "Nêu rõ số CPU dành cho hypervisor.",
    "ram_danh_cho_hypervisor_gb": "Nêu rõ RAM (GB) dành cho hypervisor.",
    "cpu_may_chu": "Nêu rõ số CPU của máy chủ.",
    "tong_cpu": "Nêu rõ tổng số CPU cần cấp.",
    "tong_ram_gb": "Nêu rõ tổng RAM (GB) cần cấp.",
    "tong_vcpu_vat_ly": "Nêu rõ tổng vCPU vật lý của cụm/host.",
    "doc_ghi_ngau_nhien_cao": "Ổ có chế độ đọc/ghi ngẫu nhiên cao không?",
    "phan_he_co_du_lieu_can_sao_luu": "Liệt kê phân hệ có dữ liệu cần sao lưu.",
    "so_ban_backup": "Khai rõ số bản backup cần giữ.",
    "so_ban_luu": "Khai rõ số bản lưu (số copy) của dữ liệu.",
    "tong_so_o": "Khai rõ tổng số ổ đĩa của hệ lưu trữ.",
    "bac_co_che_khai": "Nêu rõ bậc cơ chế (kinh doanh/hỗ trợ) đã khai.",
    "bac_co_che_yeu_cau": "Nêu rõ bậc cơ chế yêu cầu theo quy định.",
    "muc_do_quan_trong": "Nêu rõ mức độ quan trọng của hệ thống.",
}


def cau_hoi_cho(tham_so: str, goi_y_rules: dict[str, str] | None = None) -> str:
    """Câu hỏi tiếng Việt cho một tham số thiếu.

    Ưu tiên `tham_so_goi_y` trong rules.yaml (NT3 — người nghiệp vụ sửa được),
    fallback về map trong module này. Không có cả hai thì trả về tên tham số
    nguyên trạng (không bịa thêm ý nghĩa — NT4).
    """
    if goi_y_rules:
        v = goi_y_rules.get(tham_so)
        if v and v.strip():
            return v.strip()
    return _CAU_HOI.get(tham_so, tham_so)
